[package]
name        = "flix-kure"
description = "The start of a Flix port of Haskell's KURE library."
version     = "0.1.0"
flix        = "0.55.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]


